### ISSUE TITLE
Output files in copy-framework accio phase

### ISSUE THREAD

**Issue by alphatroya** [JamitLabs/Accio#13]
[Carthage instruction](https://github.com/Carthage/Carthage#getting-started) suggest specifying an output files parameter to optimise "dirty" build timing.

But Accio look like skip this recommendation, is this an intended behaviour?

**Comment by Jeehut** [comment]
No, it's not intended to ignore this, we just got used to the way of using Carthage before this feature was introduced and since it's not required, we never got used to it. But it definitely makes sense to add it to Accio if there are no risks for side effects and the build time is optimized. Thanks for the suggestion! I will have a look into this shortly.
