### ISSUE TITLE
Clarification on Carthage requirement?

### ISSUE THREAD

**Issue by MaxDesiatov** [JamitLabs/Accio#17]
HI @Dschee, thank you for this great project!

I'm a bit confused by Carthage being a requirement stated in README. As far as I understand, SwiftPM is used for dependency resolution, but most of the explanation in README focused on comparing Accio to Carthage. My understanding was that Accio is able to replace Carthage fully in a given project?

Hope this can be clarified, I'd be happy to submit a PR that makes this clear in the README as soon as I have a better understanding of this.

**Comment by Jeehut** [comment]
Hi @MaxDesiatov,

as mentioned in the README in the [Adding Dependencies](https://github.com/JamitLabs/Accio#adding-dependencies) section in point 1, Accio uses Carthage's `build` command to make sure we have wide compatibility today.

The alternative would have been to use `xcodebuild` directly and in the middle term that might be added and tested out and once it's proved to work well in many projects, we might drop usage of Carthage and use Xcode directly. But we opted for Carthage's `build` command to have a fail safe and proven to work way of starting this project out. This way if a project is compatible with Carthage and has a Package.swift manifest, it's already compatible with Accio – this makes things easier for everybody.

Note that we don't hate Carthage or anything like that, we just couldn't get some features working using Carthage and thought those features were so important that we should start a new dependency manager. Then, once decided to make a new one, we thought it would be the tedious for the community to switch to a dependency manager to only move on to SwiftPM two years later. That's why we thought about it from the other side: What if we could provide the missing parts for SwiftPM and drop our additions once get implemented right within SwiftPM?

Using this approach, we tried to use SwiftPM directly to build the frameworks, but it was clear that this didn't work, either the builds failed on SwiftPM side or Xcode didn't accept the build products. We even tried doing dependency resolving and having an own manifest to be more independent, but that approach failed even for our own projects (you can find it's leftovers [here](https://github.com/JamitLabs/SwiftDependencyManager)).

So, Accio basically is a very pragmatic approach to get as much as possible from SwiftPM to work for iOS/tvOS/macOS/watchOS projects and using Carthage's `build` command (and only that) for compatibility purposes. We could drop that easily though in the short term by replicating the used parts of Carthage within Accio – I just created an issue to track that: https://github.com/JamitLabs/Accio/issues/18.

I hope I could answer your question.

**Comment by Jeehut** [comment]
Since I got an upvote from @MaxDesiatov without further questions, I consider this question answered. So I'm closing this issue.
