### ISSUE TITLE
Be excellent to each other

### ISSUE THREAD

**Issue by tonyarnold** [JamitLabs/Accio#19]
I found the rambling hit piece on the maintainers of Carthage in your read me to be pretty confronting. 

I believe you're doing your own OSS project & contributions a disservice by dunking on other unpaid OSS maintainers. 

Your justification for building this tool stands up without needing to take a swipe at Carthage's maintainers — I'd urge you to think about rewording your readme to make it about the positive aspects of why your project is a good choice.

**Comment by Jeehut** [comment]
@tonyarnold Thank you for opening that topic. You're right, of course. I knew there was a big risk for me of being negative when writing that section. I even tried being as objective as it was possible for me to not go to a personal level. But if you say that it is too confronting, you must be right.

Since I'm still pretty biased though (I don't think I will ever forget how frustrating the discussion in https://github.com/Carthage/Carthage/pull/1990 had been), I'm not sure which parts exactly are too harsh, so it would be great if you could just change the section in a way that it is more positive and post a PR. I'd happily merge that. Would that be okay with you?

**Comment by srdanrasic** [comment]
The negativity about Carthage left a bad first impression on me. 

Carthage has issues and we may not like how it’s maintained, but it has been a valuable tool in the community and our lives be so much harder without it than they are with its flaws.

I’m looking forward to a more positive readme.

**Comment by Jeehut** [comment]
I just merged #20 and hope this issue is fixed now. Sorry for being negative in the first place.
Please also note that I don't hate Carthage at all, as I hope I already expressed in [this comment](https://github.com/Carthage/Carthage/pull/1990#issuecomment-479442640).
