### ISSUE TITLE
Project with mixed languages is not supported?

### ISSUE THREAD

**Issue by jjorn** [JamitLabs/Accio#3]
It seems that the framework may not support a (Swift based) project containing one or more Obj-c files. All dependencies could be resolved but the dependency graph not.

Log:

`✨ Resolving dependencies ...`
`⏳ Executing 'swift package --package-path '/Users/.../Project-iOS' --build-path '/Users/.../Project-iOS/.accio' resolve'`
`✨ Reading package manifest at /Users/.../Project-iOS/Package.swift ...`
`✨ Generating dependency graph ...`
`❌ 'Project-iOS' /Users/.../Project-iOS: error: target at '/Users/.../Project-iOS/App' contains mixed language source files; feature not supported`
`An error occurred: dependencyGraphGenerationFailed`

**Comment by Jeehut** [comment]
Thanks for reporting the issue @jjorn!

Yes, that's right. Since Accio uses `SwiftPM` as its core (e.g. for dependency resolution) it also shares some of its pitfalls (while others may be worked around within Accio). But this is a known restriction, the `path` parameter of the iOS project needs to only contain Swift files.

This was already documented in the [Initialization section](https://github.com/JamitLabs/Accio#initialization) of the README as follows:

> Also note that the specified path must be a directory recursively containing at least one Swift file – but mixing with other languages like (Objective-)C(++) is not supported, so they shouldn't be within the specified directory. The files in there will not be built, they just need to exist in order for SwifPM to work properly, so you could point this anywhere Swift-only code.

So just use a subdirectory within your project that contains only Swift files.

I hope this clarifies the issue. We could add a hint in the Accio error output on how to fix this as kind of a fix. Until then I'll keep this open.

**Comment by jjorn** [comment]
@Dschee Sorry my bad. I should read it carefully. By the way, thank for the quick reply.
