### ISSUE TITLE
Integrate Swift library with mixed dependencies

### ISSUE THREAD

**Issue by yvbeek** [JamitLabs/Accio#39]
Thank you for your work on Accio!

I'm considering adding Accio support to [Telegraph](https://github.com/Building42/Telegraph), but I have a few questions.

1. Telegraph itself is 100% Swift, but it has dependencies that contain Objective-C and C. Will I be able to use Accio for Telegraph?

2. Should the dependent projects (HTTPParserC and CocoaAsyncSocket) also have a Package.swift file?

3. Telegraph has a workspace with separate OS targets (iOS, macOS, tvOS), some tests and an examples project. Will there be additional steps required for people to try out the examples when I switch to Accio (I'm now using Carthage)? Is there perhaps a similar library that is already using Accio that I can have a look at?

4. Does Accio play well with Travis?

**Comment by Jeehut** [comment]
Hi @Zyphrax and thank you for considering to add Accio support to Telegraph.

1. Yes, if your dependencies can be built with Carthage (which they can), then they can also be built with Accio. It's as easy as that since Accio is using Carthage for the build task internally. For more information, read the "A practical Approach for fast Adoption" section in my blog post about Accio [here](https://medium.com/@Dschee/accio-swiftpm-for-ios-co-today-ab4d19cefb74).

2. Yes, all non-development dependencies of Telegraph need to also support Accio and for that a `Package.swift` file is needed. Please note that I already posted a PR to CocoaAsyncSocket which was not merged yet [here](https://github.com/robbiehanson/CocoaAsyncSocket/pull/679), so you can use my fork instead. Only HTTPParserC is left to be fixed, then.

3. As for the Demo project, usually you have to opt for one way of installing dependencies and users have to use the Demo project that way. If you already have Carthage configured there and have explanations on how to get started with it, you can keep it that way or decide to migrate to Accio – either way would be fine and you'd still support Accio.

As for an example project, you can find a [Demo project](https://github.com/JamitLabs/Accio/blob/stable/Demo/Package.swift) within Accio itself where I have integrated several popular dependencies for integration testing purposes. You would just need to configure your dependency with a local path instead of a GitHub URL. Please refer to the official [Package Manifest Docs](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#dependencies) for that.

4. Depends on what you consider to "play well". Basically, you can install Accio on Travis via Homebrew and run any commands, just like you would on your local machine. If your goal is to check if installation of your framework via Accio works (like you might already have for Carthage & CocoaPods), then please note that is currently in development and tracked in https://github.com/JamitLabs/Accio/issues/16. Once it's implemented, you will be able to run commands like `accio supports ios,tvOS` which will fail if installation fails for CI testing purposes.

I hope I could answer your questions. I will close this though since it's not really an "issue" but more like a question thread. Feel free to ask more questions, I will get notified even if this is closed.
