### ISSUE TITLE
Integration with XcodeGen

### ISSUE THREAD

**Issue by AlexisQapa** [JamitLabs/Accio#45]
Hi,

I'm using XcodeGen to manage my Xcode project and Carthage for dependencies. I'm trying to reduce my CI builds time with some cache but I don't want to introduce Rome.
I like your approach targeting SPM for the long run. So I'll be soon looking at a solution to integrate XcodeGen and Accio. I saw you have commands related to the .xcproject file do you think the two tools are complementary or not ?

**Comment by Jeehut** [comment]
@AlexisQapa Thank you for considering to use Accio in your setup. I have never used XcodeGen though and as far as I can tell from having a cursory look to its README, I think it might not work as expected right out of the batch since Accio is actually modifying an existing Xcode project file. If there is none, then there's nothing to modify. But if the developers always generate the project file first (using XcodeGen) and install dependencies afterwards, it should actually work.

Having that said, we could also integrate first-hand support for XcodeGen-based projects either by adding an option in Accio or by adding such a feature to XcodeGen since I read that it also works with Carthage out-of-the-box, so maybe we could add support for Accio as well? Should be much different from what is done within XcodeGen. We might need to add an option to turn off automatic integration into Xcode within Accio though (which should be easy) for this. Maybe something along the lines of `--skip-xcode-integration`?

**Comment by AlexisQapa** [comment]
Carthage integration in Xcodegen simply link already built dependencies to the right target and make a copy phase. I think that resolving packages and building them would be sufficient for a first step. You right, the only thing needed for now on the Accio part is disabling Xcode integration. As of curiosity what modifications do Accio to the Xcode project ?

**Comment by Jeehut** [comment]
You can read more about what Accio is doing in Xcode in [this article](https://medium.com/@Dschee/accio-swiftpm-for-ios-co-today-ab4d19cefb74) also linked in the README. The related text starts with the words "Note how Accio automatically added ..." – feel free to search for them to get directly to your answer.

**Comment by fredpi** [comment]
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).
