### ISSUE TITLE
Mint support

### ISSUE THREAD

**Issue by AlexisQapa** [JamitLabs/Accio#46]
Mint is package manager targeting command line tools written in swift. https://github.com/yonaskolb/Mint. Adding support should not be difficult I think and this tools is quite convenient compared to brew to manage those kind of tools.

**Comment by Jeehut** [comment]
Accio is a SwiftPM-based command line tool. Therefore it should automatically work with Mint out of the box. Back then when I first developed Accio, it wasn't compatible due to SwiftSyntax not linking correctly. But since Swift 5 linking has changed and it should work, I guess. Did you try?

One thing we could do is to document the support in the README. Feel free to post a PR for that! ;)

**Comment by AlexisQapa** [comment]
Didn't had time to try but will definitely. I'll open a PR
